insert into Persona values
(200,"Miguel","Fernandez"),
("","Marcelo","Juarez"),
("","Margarita","Hidalgo"),
("","Nicolas","Maduro"),
("","Luis","Rodriguez"),
("","Melian","Moreno"),
("","Juan","Garcia"),
("","Pedro","Peña"),
("","Matias","Benitez"),
("","Micaela","Fuentes"),
("","Dylan","Toscano"),
("","Sofia","Cristalino"),
("","Federico","Cristalino"),
("","Claudia","Laprida"),
("","Blanca","Quiroga"),
("","Bianca","Soto"),
("","Franco","Rodriguez"),
("","Bianca","Soto"),
("","Victoria","Cespedes"),
("","Jamil","Cespedes"),
("","Facundo","Abadi"),
("","Martin","Martinez"),
("","Fiorela","Vazquez"),
("","Antonio","Costas"),
("","Manuel", "Gonzales"),
("","Jose Maria","Mayo"),
("","Hernan","Hernandez"),
("","Juan","Dominguez"),
("","Julio","Domingo"),
("","Julia","Ramirez"),
("","Nadia","Guarani"),
("","Kevin","Guarani"),
("","Raul","Damonte"),
("","Miguel","Fernandez"),
("","Anastasia","Romanov"),
("","Micaela","Suarez"),
("","Gustavo","Lopez"),
("","Hector","Caceres"),
("","Osvaldo","Correa"),
("","Joaquin","Ragonese"),
("","Daniel","Alvarez"),
("","Matias","de la Fuente"),
("","Pablo","Cortez"),
("","Emiliano","Estrada"),
("","Loana","Albear"),
("","Samuel","Ontiveros"),
("","Alan","Gomez"),
("","Maximiliano","Ibarra"),
("","Sara","Gustani"),
("","Maria","Martines"),
("","Luciano","Florian"),
("","Maximiliano","Power"),
("","Abel","Muruchi"),
("","Samuel","Condori"),
("","Nicolas","Marquez"),
("","Mariano","Yanani"),
("","Matias","Hernandez"),
("","Isa","Perez"),
("","Matias","Diaz"),
("","Mateo","Hirandez"),
("","Juan","Motta"),
("","Thiago","Martinez"),
("","Thiago","Fernandez"),
("","Fabian","Gutierrez"),
("","Ludmila","Perez"),
("","David","Rojas"),
("","Julio","Argüello"),
("","Patricio","Tamayo"),
("","Modesto","Diaz"),
("","Aziz","Sevillano"),
("","Alicia","Vico"),
("","Sofia","Moreyra"),
("","Carlos", "Moreno"),
("","Mariano", "Caseres"),
("","Maria Laura","Fernandez"),
("","Ricardo", "Bragados"),
("","Pablo", "Lampone"),
("","Daniel","Caamanio"),
("","Miguel", "Hidalgo"),
("","Rosalia", "Meteora"),
("","Manuel","Rejas"),
("","Adrian","Ojeda"),
("","Nicolas","Riquelme"),
("","Joaquin","Estigarribia"),
("","Ariel","Hidalgo"),
("","Marta","Rodriguez"),
("","Eric", "Smith"),
("","Angelica", "Vertruccio"),
("","Brenda", "Lagos"),
("","Ismael", "Fernandez"),
("","Jimi", "Hendrix"),
("","Estela", "Martinez"),
("","Florencia","Suarez"),
("","Juan","Perez"),
("","Ana","Gimenez"),
("","Nicolas", "Osvaldo"),
("","Jimena", "Grimaldi "),
("","Ivan", "Giulkovich"),
("","Noelia", "Giulkovich"),
("","Jose","Ramirez"),
("","Raul","Romero"),
("","Manuel", "Suarez"),
("","Gabriel", "Dominguez"),
("","Romulo", "Romualdo"),
("","Ayden", "Adebayor"),
("","Lucas", "Manuel"),
("","Agustin", "Saponare"),
("","Marisa","Tosi"),
("","Alejandro", "ermes"),
("","Carolina","Aguilar"),
("","Manuel","Diaz"),
("","Hernan","Gomez"),
("","Tomas","Peralta"),
("","Javier","Almida"),
("","Luis","Torres"),
("","Esteban","Rodriguez"),
("","Leonel", "Lopez"),
("","Angel", "Borja"),
("","Facundo", "Vinitzca"),
("","Jerónimo","Stagno"),
("","Agustin","Servantes"),
("","Matias","Antros"),
("","Tulio", "Trivinio"),
("","Lihuel","Sotto"),
("","Sergio","Rosa"),
("","Iker","Carreño"),
("","Jonatan","Valenzuela"),
("","Domingo","Aviles"),
("","Anselmo","Llorente"),
("","Felix","Galvan"),
("","Marcos","Garca"),
("","Emiliano","Yuste"),
("","Celeste","Fuertes"),
("","Dionisio Escudero"),
("","Adan","Muñoz"),
("","Ernesto","Mellado"),
("","Roger","Pellicer"),
("","Gheorghe","Giner"),
("","Javier","Alegra"),
("","Feliciano","Valdivia"),
("","Baltasar","Merino"),
("","Marti","Mesa"),
("","Irene","Novoa"),
("","Gemma","Alves"),
("","Mihaela","Gago"),
("","Juliana","Patiño"),
("","Mariam","Tortosa"),
("","Lidia","Montoro"),
("","Daniela","Escudero"),
("","Amaia","Salmeron"),
("","Saray","Duran"),
("","Mihaela","Zheng"),
("","Valeria","Vegas"),
("","Saray","Borrego"),
("","Gregoria","Coronado"),
("","Lia","Arana"),
("","Barbara","Jaime"),
("","Mihaela","Jiménez"),
("","Olivia","Gomis"),
("","Nuria","Rincon"),
("","Mireia","Hinojosa"),
("","Claudia","Montilla"),
("","Felisa","Villa"),
("","Eulalia","Martin"),
("","Sergio","Rosa"),
("","Sagrario","Pons"),
("","Marta","Poveda"),
("","Anibal","Vives"),
("","Luz","Font"),
("","Alfonso","Alcazar"),
("","Jamal","Corrales"),
("","Myriam","Duque"),
("","Nicole","Quintero"),
("","Dunia","Rial"),
("","Luz","Vives"),
("","Eric","Amaya"),
("","Jaime","Cuenca"),
("","Naiara","Andujar"),
("","Paulino","Olmos"),
("","Adil","Roca"),
("","Adelina","Zapata"),
("","Guadalupe","Melero"),
("","Mateo","Camara"),
("","Teodoro","Juarez"),
("","Antónia","Florez"),
("","Justa","Ochoa"),
("","Patricio","Echeverria"),
("","Feliciana","Huerta"),
("","Justin","Oliveira"),
("","Flora","Medina");

insert into Federacion values
(100, "Federacion Argentina de Ski y Andinismo", null),
(101, "Federacion de Ski y Snowboard de Chile", null),
(102, "U.S. Ski and Snowboard Association", null),
(103, "Ski United Kingdom Confederation", null),
(104, "Federation Francaise de Ski", null),
(105, "Real Federacion Española de Deportes de Invierno", null);

insert into Estacion values
(150, "Catedral Alta Patagonia", "Alicia M. de Justo 1848", "2944409000", 24),
("", "Las Leñas", "RP222", "26274711000", 22),
("", "Cerro Castor", "Ruta Nacional 3", "2901499301", 19),
("", "El Colorado", "Av. Kennedy 9070", "78977534", 20),
("", "Farellones", "Camino los Cóndores 1800", "66484295", 21),
("", "La Parva", "Luis Carrera 1263", "29642100", 26),
("", "Vail", "Vail Resorts Management Company", "+19708455745", 21),
("", "Aspen Highlands", "P.O.Box 1248", "+19709251220", 20),
("", "Hurricane Ridge", "PMB 218", "+13605653131", 22),
("", "Glencoe Mountain", "Glencoe Mountain", "+441855851226", 21),
("", "Glenshee", "Glenshee Ski Centre Cairnwell", "+441339741320", 23),
("", "Nevis Range", "Nevis Range Torlundy", "+441397705825", 22),
("", "Beaver Creek", "P.O. Box 7 81658", "+19707544636", 24),
("", "Tignes", "73321 Tignes", "+33479400440", 20),
("", "La Norma", "73500 La Norma France", "+33479203146", 21),
("", "Saint-Lary-Soulan", "65170 Saint-Lary", "+33562395081", 22),
("", "Sierra Nevada", "Plaza de Andalucía", "958708090", 23),
("", "Formigal", "Urbanización Formigal 22640", "+34974490000", 21),
("", "La Pinilla", "Cerezo de Arriba 40592", "+34921551113", 20);

insert into Administracion values
("100", "150"),
("100", "151"),
("100", "152"),
("100", "153"),
("100", "154"),
("101", "151"),
("101", "152"),
("101", "153"),
("101", "154"),
("101", "155"),
("102", "156"),
("102", "157"),
("102", "158"),
("102", "159"),

("103", "160"),
("103", "161"),
("103", "162"),
("103", "163"),
("103", "167"),
("104", "161"),
("104", "162"),
("104", "163"),
("104", "164"),
("104", "165"),
("104", "166"),
("105", "162"),
("105", "164"),
("105", "166"),
("105", "167"),
("105", "168");
